# -*- coding: utf-8 -*-
"""
Created on Wed Jul 22 15:12:54 2020

@author: User-1
"""

def reverse(s): 
  str = "" 
  for i in s: 
    str = i + str
  return str
s = "ACATAGTCCGTAGTCTGCGACACTCGGTCCCGTACTCCGTGTCCTCTTCGATGTACTGATGCCATCCTCGCGCTACTGAATCGATATGCTGAGGAAAGGCGATAGCTAACAACTTGCTCGGCCCCGTAGGGCGTGTTACGTACCATGGCTCTAGTACCCGACCACACAGTATACACAAAATTACTTCAAGGTTAACGCACGTTCTGTATGCACCGTTTCTGGCTCTTCTTCTCCTTAGCGTCCTTCATGCGACCATCGATAAGTTCGGATCCTCTCACGGCATCGGTTTTATAGCTAACCGGGCCAATTCACAGTCGCTCGGTCCGCTTTTTGTCGGAAGGACGACTTGTGGGATTCAGGGGCTTGGAATTGATCGGCTTTACATCTTACTTTTGAGGAGTGAAACCGGTGGATTGTTCAATTCCAACGTGCTAGGGTATGATCTGTTTGTGACCTCAGCAAATGCGACCAAGGGCTTATCGTATGTACGCAGAGCTATTTAAGGACCACTGCACCACCCTAGAATTATGCCGTCTGTTCGCTGAAGCATCTAACATTGTAACCTCCGAGTGCGCATGGGCCTTAGACGATATTGGGCCCGCTACAACGGCTGTTACGGCCAGTAGTCACCGAACTGATCCATGTGCAGCCGGCTGTGTACGCTATTCTGAGATTCGGCACACTGGATGGCAGAGCTGGGCGGATCAGTGGTACCTATGTATAAAAAAGCCCATGGCTCTGCTCGCCCGACGTGGGCATTGATTGTTACGTAGGTTGTCCAGGGCGAGCAAACAATCAACCACTACTTATGCAATTCGAAACTGTC"
string=(reverse(s))
string=string.replace('A', 't')
string=string.replace('T', 'A')
string=string.replace('C', 'g')
string=string.replace('G', 'C')
string=string.replace('g', 'G')
string=string.replace('t', 'T')
print(string)
